CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    birthdate date NOT NULL,
    height numeric(8, 2) NOT NULL,
    weight numeric(8, 2) NOT NULL,
    activity text NOT NULL
);

CREATE TABLE IF NOT EXISTS programs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    program text NOT NULL,
    schedule text NOT NULL
);

CREATE TABLE IF NOT EXISTS workouts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    workout_name text NOT NULL,
    workout_reps integer NOT NULL,
    workout_sets integer NOT NULL,
    workout_day text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_programs_user_id ON programs(user_id);
CREATE INDEX IF NOT EXISTS idx_workouts_user_id ON workouts(user_id);
CREATE INDEX IF NOT EXISTS idx_workouts_user_day ON workouts(user_id, workout_day);
