<?php

return [
    'full-body' => [
        'Full Body' => [
            ['name' => 'Incline Bench Press', 'focus' => 'Chest'],
            ['name' => 'Lat Pulldown', 'focus' => 'Back'],
            ['name' => 'Goblet Squat', 'focus' => 'Quads and Glutes'],
            ['name' => 'Romanian Deadlift', 'focus' => 'Hamstrings and Glutes'],
            ['name' => 'Lateral Raise', 'focus' => 'Shoulders'],
            ['name' => 'Cable Crunch', 'focus' => 'Core'],
        ],
        'Full Body A' => [
            ['name' => 'Bench Press', 'focus' => 'Chest'],
            ['name' => 'Seated Cable Row', 'focus' => 'Back'],
            ['name' => 'Hack Squat', 'focus' => 'Quads'],
            ['name' => 'Leg Curl', 'focus' => 'Hamstrings'],
            ['name' => 'Dumbbell Shoulder Press', 'focus' => 'Shoulders'],
            ['name' => 'Standing Calf Raise', 'focus' => 'Calves'],
        ],
        'Full Body B' => [
            ['name' => 'Incline Dumbbell Press', 'focus' => 'Upper Chest'],
            ['name' => 'Lat Pulldown', 'focus' => 'Lats'],
            ['name' => 'Walking Lunge', 'focus' => 'Quads and Glutes'],
            ['name' => 'Hip Thrust', 'focus' => 'Glutes'],
            ['name' => 'Face Pull', 'focus' => 'Rear Delts'],
            ['name' => 'Plank', 'focus' => 'Core'],
        ],
    ],
    'upper-lower' => [
        'Upper' => [
            ['name' => 'Incline Bench Press', 'focus' => 'Chest'],
            ['name' => 'Lat Pulldown', 'focus' => 'Lats'],
            ['name' => 'Seated Cable Row', 'focus' => 'Back'],
            ['name' => 'Shoulder Press', 'focus' => 'Shoulders'],
            ['name' => 'Lateral Raise', 'focus' => 'Side Delts'],
            ['name' => 'Preacher Curl', 'focus' => 'Biceps'],
            ['name' => 'Tricep Pushdown', 'focus' => 'Triceps'],
        ],
        'Lower' => [
            ['name' => 'Hack Squat', 'focus' => 'Quads'],
            ['name' => 'Romanian Deadlift', 'focus' => 'Hamstrings'],
            ['name' => 'Walking Lunge', 'focus' => 'Quads and Glutes'],
            ['name' => 'Leg Curl', 'focus' => 'Hamstrings'],
            ['name' => 'Hip Abduction', 'focus' => 'Glutes'],
            ['name' => 'Standing Calf Raise', 'focus' => 'Calves'],
            ['name' => 'Cable Crunch', 'focus' => 'Core'],
        ],
    ],
    'ppl' => [
        'Push' => [
            ['name' => 'Bench Press', 'focus' => 'Chest'],
            ['name' => 'Incline Dumbbell Press', 'focus' => 'Upper Chest'],
            ['name' => 'Cable Fly', 'focus' => 'Chest'],
            ['name' => 'Shoulder Press', 'focus' => 'Shoulders'],
            ['name' => 'Lateral Raise', 'focus' => 'Side Delts'],
            ['name' => 'Tricep Pushdown', 'focus' => 'Triceps'],
        ],
        'Pull' => [
            ['name' => 'Lat Pulldown', 'focus' => 'Lats'],
            ['name' => 'Chest Supported Row', 'focus' => 'Back'],
            ['name' => 'Seated Cable Row', 'focus' => 'Back'],
            ['name' => 'Face Pull', 'focus' => 'Rear Delts'],
            ['name' => 'Preacher Curl', 'focus' => 'Biceps'],
            ['name' => 'Hammer Curl', 'focus' => 'Brachialis'],
        ],
        'Legs' => [
            ['name' => 'Hack Squat', 'focus' => 'Quads'],
            ['name' => 'Romanian Deadlift', 'focus' => 'Hamstrings'],
            ['name' => 'Walking Lunge', 'focus' => 'Quads and Glutes'],
            ['name' => 'Leg Curl', 'focus' => 'Hamstrings'],
            ['name' => 'Calf Raise', 'focus' => 'Calves'],
            ['name' => 'Cable Crunch', 'focus' => 'Core'],
        ],
    ],
    'pplul' => [
        'Push' => [
            ['name' => 'Bench Press', 'focus' => 'Chest'],
            ['name' => 'Incline Dumbbell Press', 'focus' => 'Upper Chest'],
            ['name' => 'Cable Fly', 'focus' => 'Chest'],
            ['name' => 'Shoulder Press', 'focus' => 'Shoulders'],
            ['name' => 'Lateral Raise', 'focus' => 'Side Delts'],
            ['name' => 'Tricep Pushdown', 'focus' => 'Triceps'],
        ],
        'Pull' => [
            ['name' => 'Lat Pulldown', 'focus' => 'Lats'],
            ['name' => 'Chest Supported Row', 'focus' => 'Back'],
            ['name' => 'Seated Cable Row', 'focus' => 'Back'],
            ['name' => 'Face Pull', 'focus' => 'Rear Delts'],
            ['name' => 'Preacher Curl', 'focus' => 'Biceps'],
            ['name' => 'Hammer Curl', 'focus' => 'Brachialis'],
        ],
        'Legs' => [
            ['name' => 'Hack Squat', 'focus' => 'Quads'],
            ['name' => 'Romanian Deadlift', 'focus' => 'Hamstrings'],
            ['name' => 'Walking Lunge', 'focus' => 'Quads and Glutes'],
            ['name' => 'Leg Curl', 'focus' => 'Hamstrings'],
            ['name' => 'Calf Raise', 'focus' => 'Calves'],
            ['name' => 'Cable Crunch', 'focus' => 'Core'],
        ],
        'Upper' => [
            ['name' => 'Incline Bench Press', 'focus' => 'Chest'],
            ['name' => 'Lat Pulldown', 'focus' => 'Lats'],
            ['name' => 'T-Bar Row', 'focus' => 'Back'],
            ['name' => 'Pec Deck', 'focus' => 'Chest'],
            ['name' => 'Lateral Raise', 'focus' => 'Side Delts'],
            ['name' => 'Hammer Curl', 'focus' => 'Biceps'],
            ['name' => 'Tricep Pushdown', 'focus' => 'Triceps'],
        ],
        'Lower' => [
            ['name' => 'Hack Squat', 'focus' => 'Quads'],
            ['name' => 'Leg Press', 'focus' => 'Quads'],
            ['name' => 'Romanian Deadlift', 'focus' => 'Hamstrings'],
            ['name' => 'Leg Curl', 'focus' => 'Hamstrings'],
            ['name' => 'Hip Abduction', 'focus' => 'Glutes'],
            ['name' => 'Calf Raise', 'focus' => 'Calves'],
            ['name' => 'Hanging Leg Raise', 'focus' => 'Core'],
        ],
    ],
    'ppl-upper-sharms' => [
        'Push' => [
            ['name' => 'Smith Machine Incline Bench Press', 'focus' => 'Upper Chest'],
            ['name' => 'Pec Deck', 'focus' => 'Mid Chest'],
            ['name' => 'High to Low Cable Fly', 'focus' => 'Chest'],
            ['name' => 'Lateral Raise', 'focus' => 'Side Delt'],
            ['name' => 'Straight Bar Tricep Pushdown', 'focus' => 'Long Head Triceps'],
            ['name' => 'Overhead Cable Triceps Extension', 'focus' => 'Short Head Triceps'],
        ],
        'Pull' => [
            ['name' => 'Lat Pulldown', 'focus' => 'Back'],
            ['name' => 'Chest Supported Row', 'focus' => 'Back'],
            ['name' => 'Cable Seated Row', 'focus' => 'Back'],
            ['name' => 'Preacher Curl', 'focus' => 'Short Head Biceps'],
            ['name' => 'Hammer Curl', 'focus' => 'Brachialis'],
            ['name' => 'Reverse Pec Deck', 'focus' => 'Rear Delt'],
        ],
        'Legs' => [
            ['name' => 'Hack Squat', 'focus' => 'Legs'],
            ['name' => 'Walking Lunge', 'focus' => 'Quads'],
            ['name' => 'Calf Raise', 'focus' => 'Calves'],
            ['name' => 'Hip Abduction', 'focus' => 'Glutes'],
            ['name' => 'Hamstring Curl', 'focus' => 'Hamstrings'],
            ['name' => 'Cable Crunch', 'focus' => 'Upper and Lower Abs'],
            ['name' => 'Supported Leg Raise', 'focus' => 'Lower Abs'],
        ],
        'Upper' => [
            ['name' => 'High to Low Cable Fly', 'focus' => 'Chest'],
            ['name' => 'Pec Deck', 'focus' => 'Mid Chest'],
            ['name' => 'Lat Prayer', 'focus' => 'Lats'],
            ['name' => 'T-Bar Row', 'focus' => 'Back'],
            ['name' => 'Cable Seated Row', 'focus' => 'Back'],
        ],
        'ShArms' => [
            ['name' => 'Preacher Curl', 'focus' => 'Short Head Biceps'],
            ['name' => 'Hammer Curl', 'focus' => 'Brachialis'],
            ['name' => 'Straight Bar Tricep Pushdown', 'focus' => 'Long Head Triceps'],
            ['name' => 'Overhead Cable Triceps Extension', 'focus' => 'Short Head Triceps'],
            ['name' => 'Lateral Raise', 'focus' => 'Side Delt'],
            ['name' => 'Shoulder Press', 'focus' => 'Front Delt'],
        ],
    ],
    'arnold' => [
        'Chest + Back' => [
            ['name' => 'Bench Press', 'focus' => 'Chest'],
            ['name' => 'Incline Bench Press', 'focus' => 'Upper Chest'],
            ['name' => 'Pec Deck', 'focus' => 'Chest'],
            ['name' => 'Lat Pulldown', 'focus' => 'Lats'],
            ['name' => 'T-Bar Row', 'focus' => 'Back'],
            ['name' => 'Seated Cable Row', 'focus' => 'Back'],
        ],
        'Shoulders + Arms' => [
            ['name' => 'Shoulder Press', 'focus' => 'Shoulders'],
            ['name' => 'Lateral Raise', 'focus' => 'Side Delts'],
            ['name' => 'Reverse Pec Deck', 'focus' => 'Rear Delts'],
            ['name' => 'Preacher Curl', 'focus' => 'Biceps'],
            ['name' => 'Hammer Curl', 'focus' => 'Brachialis'],
            ['name' => 'Tricep Pushdown', 'focus' => 'Triceps'],
            ['name' => 'Overhead Cable Triceps Extension', 'focus' => 'Triceps'],
        ],
        'Legs' => [
            ['name' => 'Hack Squat', 'focus' => 'Quads'],
            ['name' => 'Romanian Deadlift', 'focus' => 'Hamstrings'],
            ['name' => 'Walking Lunge', 'focus' => 'Quads and Glutes'],
            ['name' => 'Leg Curl', 'focus' => 'Hamstrings'],
            ['name' => 'Calf Raise', 'focus' => 'Calves'],
            ['name' => 'Cable Crunch', 'focus' => 'Core'],
        ],
    ],
    'bro-split' => [
        'Chest' => [
            ['name' => 'Bench Press', 'focus' => 'Mid Chest'],
            ['name' => 'Incline Bench Press', 'focus' => 'Upper Chest'],
            ['name' => 'Pec Deck', 'focus' => 'Chest'],
            ['name' => 'High to Low Cable Fly', 'focus' => 'Lower Chest'],
            ['name' => 'Cable Crossover', 'focus' => 'Chest'],
        ],
        'Back' => [
            ['name' => 'Lat Pulldown', 'focus' => 'Lats'],
            ['name' => 'T-Bar Row', 'focus' => 'Mid Back'],
            ['name' => 'Chest Supported Row', 'focus' => 'Back'],
            ['name' => 'Seated Cable Row', 'focus' => 'Back'],
            ['name' => 'Lat Prayer', 'focus' => 'Lats'],
            ['name' => 'Face Pull', 'focus' => 'Rear Delts'],
        ],
        'Legs' => [
            ['name' => 'Hack Squat', 'focus' => 'Quads'],
            ['name' => 'Leg Press', 'focus' => 'Quads'],
            ['name' => 'Romanian Deadlift', 'focus' => 'Hamstrings'],
            ['name' => 'Walking Lunge', 'focus' => 'Quads and Glutes'],
            ['name' => 'Leg Curl', 'focus' => 'Hamstrings'],
            ['name' => 'Calf Raise', 'focus' => 'Calves'],
            ['name' => 'Hip Abduction', 'focus' => 'Glutes'],
        ],
        'Shoulders' => [
            ['name' => 'Shoulder Press', 'focus' => 'Front Delts'],
            ['name' => 'Lateral Raise', 'focus' => 'Side Delts'],
            ['name' => 'Reverse Pec Deck', 'focus' => 'Rear Delts'],
            ['name' => 'Face Pull', 'focus' => 'Rear Delts'],
            ['name' => 'Shrug', 'focus' => 'Traps'],
        ],
        'Arms + Abs' => [
            ['name' => 'Preacher Curl', 'focus' => 'Biceps'],
            ['name' => 'Hammer Curl', 'focus' => 'Brachialis'],
            ['name' => 'Tricep Pushdown', 'focus' => 'Triceps'],
            ['name' => 'Overhead Cable Triceps Extension', 'focus' => 'Triceps'],
            ['name' => 'Cable Crunch', 'focus' => 'Abs'],
            ['name' => 'Supported Leg Raise', 'focus' => 'Lower Abs'],
        ],
        'Arms' => [
            ['name' => 'Preacher Curl', 'focus' => 'Biceps'],
            ['name' => 'Barbell Curl', 'focus' => 'Biceps'],
            ['name' => 'Hammer Curl', 'focus' => 'Brachialis'],
            ['name' => 'Tricep Pushdown', 'focus' => 'Triceps'],
            ['name' => 'Overhead Cable Triceps Extension', 'focus' => 'Triceps'],
            ['name' => 'Close-Grip Bench Press', 'focus' => 'Triceps'],
        ],
        'Abs' => [
            ['name' => 'Cable Crunch', 'focus' => 'Upper and Lower Abs'],
            ['name' => 'Supported Leg Raise', 'focus' => 'Lower Abs'],
            ['name' => 'Plank', 'focus' => 'Core'],
            ['name' => 'Russian Twist', 'focus' => 'Obliques'],
            ['name' => 'Dead Bug', 'focus' => 'Core'],
        ],
    ],
];
